import os
from dotenv import load_dotenv
from agents import build_reader_agent, build_search_agent, critic_chain, writer_chain

load_dotenv()

# Running of research pipeline.
def run_research_pipeline(topic: str) -> dict:

    # Container for storing all outputs.
    state = {}

    # Searching for information about the topic.
    search_agent = build_search_agent()
    search_result = search_agent.invoke({
        "messages": [('user', f"Find the recent and reliable information about {topic}")]
    })

    state['search_result'] = search_result['messages'][-1].content

    # Deep research.
    research_agent = build_reader_agent()
    research_result = research_agent.invoke({
        "messages": [("user",
                f"Based on the following search results about '{topic}', "
                f"pick the most relevant URL and scrape it for deeper content.\n\n"
                f"Search results: \n {state['search_result'][:800]}"
        )]
    })

    state["scraped_content"] = research_result['messages'][-1].content

    # Combine both outputs of the agents.
    research_combine = (
        f"SEARCH_RESULTS : \n {state['search_result']}\n\n"
        f"DETAILED_INFORMATION : \n {state['scraped_content']}"
    )

    # Report generated by the agent.
    state['report'] = writer_chain.invoke({
        'topic': topic,
        'research': research_combine
    })

    # Feedback of the information.
    state['feedback'] = critic_chain.invoke({
        'report': state['report']
    })

    print(state)
    return state


if __name__ == "__main__":
    query = input("Enter topic: ")
    run_research_pipeline(query)